
title: Jack Chubick
email: 
description: 
baseurl: "" 
url: "igobyjack.vercel.app"   

# build settings
theme: 
plugins:
  - jekyll-feed

# Add MIME type support for video files
include:
  - assets

# Serve static files properly
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"



# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
