
title: Jack Chubick
email: 
description: 
baseurl: "" 
url: "igobyjack.vercel.app"   

# build settings
theme: 
plugins:
  - jekyll-feed



# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
